# Generated by Django 5.1.15 on 2026-02-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalData', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'verbose_name': 'General Settings', 'verbose_name_plural': 'General Settings'},
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='cel',
            field=models.CharField(blank=True, help_text='WhatsApp number (e.g., 76644033)', max_length=12, null=True, verbose_name='WhatsApp / Celular 1'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='cel2',
            field=models.CharField(blank=True, help_text='Secondary phone number', max_length=12, null=True, verbose_name='Celular 2'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email (e.g., serprolim@limpiezapozossepticos.com)', max_length=255, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='mjeGlobo',
            field=models.CharField(blank=True, help_text='Leave blank to hide WhatsApp bubble', max_length=128, null=True, verbose_name='WhatsApp Bubble Message'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='tel',
            field=models.CharField(blank=True, help_text='Phone number (e.g., 3215779)', max_length=12, null=True, verbose_name='Phone'),
        ),
    ]
