# Generated by Django 5.1.15 on 2026-02-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalData', '0005_alter_generalsettings_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='theme',
            field=models.CharField(choices=[('serprolim', 'Serprolim (Original)'), ('limpio', 'Limpio (Compatible)')], default='serprolim', help_text='Select the color palette for the site', max_length=50, verbose_name='Theme / Palette'),
        ),
    ]
