# Generated by Django 5.1.15 on 2026-02-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalData', '0007_alter_generalsettings_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='theme',
            field=models.CharField(choices=[('serprolim', 'Serprolim (Original)'), ('limpio', 'Limpio (Compatible)'), ('limpio-ya', 'Limpio Ya (Logo Colors)'), ('multisane', 'MultiSane (Emerald Green)')], default='serprolim', help_text='Select the color palette for the site', max_length=50, verbose_name='Theme / Palette'),
        ),
    ]
