# Generated by Django 5.1.15 on 2026-02-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalData', '0010_migrate_general_to_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrysettings',
            name='body_scripts',
            field=models.TextField(blank=True, help_text='Add tracking scripts toward closing <body> tag.', null=True, verbose_name='<body> tracking scripts'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='facebook page', null=True),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='ga_g_tracking_id',
            field=models.CharField(blank=True, help_text='Your Google Analytics 4 tracking ID (begins with "G-")', max_length=255, verbose_name='G Tracking ID'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='gads_id',
            field=models.CharField(blank=True, help_text='Begins with "AW-"', max_length=255, verbose_name='Google Ads ID'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='gtm_id',
            field=models.CharField(blank=True, help_text='Begins with "GTM-"', max_length=255, verbose_name='Google Tag Manager ID'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='head_scripts',
            field=models.TextField(blank=True, help_text='Add tracking scripts between the <head> tags.', null=True, verbose_name='<head> tracking scripts'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='instagram', null=True),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='tiktok',
            field=models.URLField(blank=True, help_text='tiktok', null=True),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='youtube channel', null=True),
        ),
    ]
