# Generated by Django 5.1.15 on 2026-02-07 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('generalData', '0012_migrate_social_analytics_pivot'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrysettings',
            name='cotizaDescription',
            field=models.TextField(blank=True, help_text='Descripcion Cotizar', max_length=350, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='displayNServicios',
            field=models.BooleanField(default=True, help_text='Mostrar Cards de Nuestros Segicios', verbose_name='Mostrar'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='imageBG',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Background Image'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='imageMain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Main Image'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='imagePromo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Promo Image'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='mjeCotiza',
            field=models.CharField(blank=True, help_text='Mensaje de Cotiza una que se selecciona el lugar', max_length=200, null=True, verbose_name='Cotiza'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='mjeFueraDeRango',
            field=models.CharField(blank=True, help_text='La posición esta fuera del rango que se tiene en los mapas', max_length=200, null=True, verbose_name='Fuera de Rango'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='mjeWAContratando',
            field=models.CharField(blank=True, help_text='Mensaje Whatsapp Contratando servicio', max_length=200, null=True, verbose_name='Whatsapp Contratando'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='mjeWAFueraDeRango',
            field=models.CharField(blank=True, help_text='Mensaje Whatsapp fuera de rango', max_length=200, null=True, verbose_name='Whatsapp Fuera de rango'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='serviviosDescription',
            field=models.TextField(blank=True, help_text='Nuestros Servicios', max_length=350, null=True, verbose_name='Servicios'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='slogan',
            field=models.TextField(blank=True, help_text='Slogan', null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subitulo', max_length=50, null=True, verbose_name='Sub Titulo'),
        ),
    ]
