# Generated by Django 5.1.15 on 2026-02-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalData', '0013_countrysettings_cotizadescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrysettings',
            name='cotizaDescription',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='displayNServicios',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='imageBG',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='imageMain',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='imagePromo',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='mjeCotiza',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='mjeFueraDeRango',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='mjeWAContratando',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='mjeWAFueraDeRango',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='serviviosDescription',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='subtitle',
        ),
    ]
