# Generated by Django 6.0.2 on 2026-02-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalData', '0014_remove_countrysettings_cotizadescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrysettings',
            name='site_name',
            field=models.CharField(blank=True, default='SerProLim', help_text='Brand name for this country (overrides General Settings)', max_length=100, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='countrysettings',
            name='site_url',
            field=models.URLField(blank=True, help_text='Full canonical URL for this country (e.g., https://limpiezapozossepticos.com)', null=True, verbose_name='Site URL'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site_name',
            field=models.CharField(default='SerProLim', help_text='Brand name shown in titles, alt texts and meta tags (e.g., SerProLim)', max_length=100, verbose_name='Site Name'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site_url',
            field=models.URLField(blank=True, help_text='Full canonical URL of the site (e.g., https://limpiezapozossepticos.com)', null=True, verbose_name='Site URL'),
        ),
    ]
