# Generated by Django 5.1.15 on 2026-02-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalData', '0018_migrate_analytics_to_wanalytics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrysettings',
            name='body_scripts',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='ga_g_tracking_id',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='gads_id',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='gtm_id',
        ),
        migrations.RemoveField(
            model_name='countrysettings',
            name='head_scripts',
        ),
    ]
