# Generated by Django 5.1.15 on 2026-02-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalData', '0019_remove_analytics_from_countrysettings'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='social',
                    table='wgeneraldata_social',
                ),
            ],
            database_operations=[],  # Table already exists with this name
        ),
    ]
