# Generated by Django 4.1.1 on 2022-09-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, help_text='Business address', max_length=255, null=True, verbose_name='Address')),
                ('lat', models.FloatField(blank=True, max_length=12, null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, max_length=12, null=True, verbose_name='Longitude')),
                ('tel', models.CharField(blank=True, help_text='+591 3XXXXXXXX', max_length=12, null=True, verbose_name='Phone')),
                ('cel', models.CharField(blank=True, help_text='+591 XXXXXXXX Whatsapp', max_length=12, null=True, verbose_name='celular phone 1 ')),
                ('mjeGlobo', models.CharField(blank=True, help_text='En caso dejar en blanco, no se mostrara el globo', max_length=128, null=True, verbose_name='Mensaje Globo whatsapp')),
                ('cel2', models.CharField(blank=True, help_text='+591 XXXXXXXX', max_length=12, null=True, verbose_name='celular phone 2')),
                ('email', models.CharField(blank=True, help_text='The default email address this site appears to send from. For example: "sender@example.com" or "Sender Name <sender@example.com>" (without quotes)', max_length=255, null=True, verbose_name='email address')),
            ],
            options={
                'verbose_name': 'General Data',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='facebook page', null=True)),
                ('instagram', models.URLField(blank=True, help_text='instagram', null=True)),
                ('tiktok', models.URLField(blank=True, help_text='tiktok', null=True)),
                ('youtube', models.URLField(blank=True, help_text='youtube channel', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
