# Generated by Django 5.1.15 on 2026-02-05 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('config', '0002_alter_generalsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='Website icon/logo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Icon'),
        ),
    ]
