# Generated by Django 6.0.2 on 2026-02-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_countrysettings_site_name_countrysettings_site_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrysettings',
            name='site_name',
            field=models.CharField(blank=True, default='MultiSane', help_text='Brand name for this country (overrides General Settings)', max_length=100, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='countrysettings',
            name='theme',
            field=models.CharField(choices=[('multisane', 'MultiSane (Original)'), ('limpio', 'Limpio (Compatible)'), ('limpio-ya', 'Limpio Ya (Logo Colors)'), ('multisane', 'MultiSane (Emerald Green)')], default='multisane', help_text='Select the color palette for this country', max_length=50, verbose_name='Theme / Palette'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='site_name',
            field=models.CharField(default='MultiSane', help_text='Brand name shown in titles, alt texts and meta tags (e.g., MultiSane)', max_length=100, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='theme',
            field=models.CharField(choices=[('multisane', 'MultiSane (Original)'), ('limpio', 'Limpio (Compatible)'), ('limpio-ya', 'Limpio Ya (Logo Colors)'), ('multisane', 'MultiSane (Emerald Green)')], default='multisane', help_text='Select the color palette for the site', max_length=50, verbose_name='Theme / Palette'),
        ),
    ]
