# Generated by Django 5.1.15 on 2026-02-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_alter_countrysettings_site_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email (e.g., contacto@tudominio.com)', max_length=255, null=True, verbose_name='Email Address'),
        ),
    ]
