# Generated by Django 4.1.1 on 2022-09-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='search_image',
        ),
    ]
