# Generated by Django 4.1.1 on 2022-09-28 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0002_remove_homepage_search_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntasfrecuentes',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='cotizaDescription',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='displayNServicios',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='imageBG',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='imageMain',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='imagePromo',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='mjeCotiza',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='mjeFueraDeRango',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='mjeWAContratando',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='mjeWAFueraDeRango',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='serviviosDescription',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slogan',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image'),
        ),
        migrations.DeleteModel(
            name='nuestrosServicios',
        ),
        migrations.DeleteModel(
            name='preguntasFrecuentes',
        ),
    ]
