# Generated by Django 4.1.1 on 2022-09-28 22:23

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0003_remove_preguntasfrecuentes_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cotizaDescription',
            field=models.TextField(blank=True, help_text='Descripcion Cotizar', max_length=350, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='displayNServicios',
            field=models.BooleanField(default=True, help_text='Mostrar Cards de Nuestros Segicios', verbose_name='Mostrar'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='imageBG',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='imageMain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='imagePromo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mjeCotiza',
            field=models.CharField(blank=True, help_text='Mensaje de Cotiza una que se selecciona el lugar', max_length=200, null=True, verbose_name='Cotiza'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mjeFueraDeRango',
            field=models.CharField(blank=True, help_text='La posición esta fuera del rango que se tiene en los mapas', max_length=200, null=True, verbose_name='Fuera de Rango'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mjeWAContratando',
            field=models.CharField(blank=True, help_text='Mensaje Whatsapp Contratando servicio', max_length=200, null=True, verbose_name='Whatsapp Contratando'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mjeWAFueraDeRango',
            field=models.CharField(blank=True, help_text='Mensaje Whatsapp fuera de rango', max_length=200, null=True, verbose_name='Whatsapp Fuera de rango'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='serviviosDescription',
            field=models.TextField(blank=True, help_text='Nuestros Servicios', max_length=350, null=True, verbose_name='Servicios'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slogan',
            field=models.TextField(blank=True, help_text='Slogan', null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subitulo', max_length=50, null=True, verbose_name='Sub Titulo'),
        ),
        migrations.CreateModel(
            name='preguntasFrecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('pregunta', models.CharField(blank=True, max_length=250, null=True, verbose_name='Pregunta')),
                ('respuesta', models.TextField(blank=True, max_length=500, null=True, verbose_name='Respuesta')),
                ('display', models.BooleanField(default=True, help_text='Mostrar Pregunta y Respuesta', verbose_name='Mostrar')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_frecuentes', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='nuestrosServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(max_length=25)),
                ('resumen', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuestros_servicios', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
