# Generated by Django 5.1.15 on 2026-02-07 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_landingpage_country'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingfaq',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='config.countrysettings', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='landingservice',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='config.countrysettings', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='landingfaq',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_frecuentes', to='home.landingpage'),
        ),
        migrations.AlterField(
            model_name='landingservice',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nuestros_servicios', to='home.landingpage'),
        ),
    ]
