# Generated by Django 5.1.15 on 2026-02-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_migrate_landing_page_pivot'),
        ('wgeneralData', '0013_countrysettings_cotizadescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Check to make this the active Landing Page for the selected country.', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='landingfaq',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs_deprecated', to='wgeneralData.countrysettings', verbose_name='Country (Deprecated)'),
        ),
        migrations.AlterField(
            model_name='landingfaq',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_frecuentes', to='home.landingpage'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='wgeneralData.countrysettings', verbose_name='Country Config'),
        ),
        migrations.AlterField(
            model_name='landingservice',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_deprecated', to='wgeneralData.countrysettings', verbose_name='Country (Deprecated)'),
        ),
        migrations.AlterField(
            model_name='landingservice',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nuestros_servicios', to='home.landingpage'),
        ),
    ]
