# Generated by Django 5.1.15 on 2026-02-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_reverse_pivot_landing_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingfaq',
            name='country',
        ),
        migrations.RemoveField(
            model_name='landingservice',
            name='country',
        ),
        migrations.AlterField(
            model_name='landingfaq',
            name='landing_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_frecuentes', to='home.landingpage'),
        ),
        migrations.AlterField(
            model_name='landingservice',
            name='landing_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nuestros_servicios', to='home.landingpage'),
        ),
    ]
