# Generated by Django 5.1.15 on 2026-02-23 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_landingfaq_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='search_description',
            field=models.TextField(blank=True, default='SerProLim - Limpieza de pozos ciegos y cámaras sépticas en Santa Cruz. Cotiza en línea. Puntualidad y buen servicio.', help_text='Descripción para buscadores (máx 160 caracteres)', max_length=160, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='seo_title',
            field=models.CharField(blank=True, default='Limpieza de pozos y cámaras sépticas', help_text='Título para buscadores y redes sociales (ej: Limpieza de pozos y cámaras sépticas)', max_length=70, null=True, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='landingfaq',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_frecuentes', to='home.landingpage'),
        ),
        migrations.AlterField(
            model_name='landingservice',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuestros_servicios', to='home.landingpage'),
        ),
    ]
