# Generated by Django 6.0.2 on 2026-03-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_deprecated_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='search_description',
            field=models.TextField(blank=True, default='MultiSane - Limpieza de pozos ciegos y cámaras sépticas en Santa Cruz. Cotiza en línea. Puntualidad y buen servicio.', help_text='Descripción para buscadores (máx 160 caracteres)', max_length=160, null=True, verbose_name='Meta Description'),
        ),
    ]
