# Generated by Django 6.0.2 on 2026-03-10 22:58

import config.metadata
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_add_standardpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, help_text='Subitulo', max_length=50, null=True, verbose_name='Sub Titulo')),
                ('slogan', models.TextField(blank=True, help_text='Slogan', null=True, verbose_name='Slogan')),
                ('cotizaDescription', models.TextField(blank=True, help_text='Descripcion Cotizar', max_length=350, null=True, verbose_name='Descripcion')),
                ('mjeCotiza', models.CharField(blank=True, help_text='Mensaje de Cotiza una que se selecciona el lugar', max_length=200, null=True, verbose_name='Cotiza')),
                ('mjeFueraDeRango', models.CharField(blank=True, help_text='La posición esta fuera del rango que se tiene en los mapas', max_length=200, null=True, verbose_name='Fuera de Rango')),
                ('mjeWAContratando', models.CharField(blank=True, help_text='Mensaje Whatsapp Contratando servicio', max_length=200, null=True, verbose_name='Whatsapp Contratando')),
                ('mjeWAFueraDeRango', models.CharField(blank=True, help_text='Mensaje Whatsapp fuera de rango', max_length=200, null=True, verbose_name='Whatsapp Fuera de rango')),
                ('serviviosDescription', models.TextField(blank=True, help_text='Nuestros Servicios', max_length=350, null=True, verbose_name='Servicios')),
                ('displayNServicios', models.BooleanField(default=True, help_text='Mostrar Cards de Nuestros Segicios', verbose_name='Mostrar')),
                ('imageBG', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('imageMain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('imagePromo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'abstract': False,
            },
            bases=(config.metadata.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='nuestrosServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(max_length=25)),
                ('resumen', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuestros_servicios', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='preguntasFrecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('pregunta', models.CharField(blank=True, max_length=250, null=True, verbose_name='Pregunta')),
                ('respuesta', models.TextField(blank=True, max_length=500, null=True, verbose_name='Respuesta')),
                ('display', models.BooleanField(default=True, help_text='Mostrar Pregunta y Respuesta', verbose_name='Mostrar')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_frecuentes', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
