# Generated by Django 5.1.15 on 2026-02-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgeneralData', '0003_generalsettings_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='icon',
            field=models.ImageField(blank=True, help_text='Website icon/logo', null=True, upload_to='icons/', verbose_name='Icon'),
        ),
    ]
