# Generated by Django 5.1.15 on 2026-02-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgeneralData', '0004_alter_generalsettings_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='icon',
            field=models.FileField(blank=True, help_text='Website icon/logo (SVG, PNG, JPG)', null=True, upload_to='icons/', verbose_name='Icon'),
        ),
    ]
