# Generated by Django 5.1.15 on 2026-02-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgeneralData', '0008_alter_generalsettings_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.SlugField(help_text='Unique code for the country (e.g., ar, py, bo)', max_length=5, unique=True, verbose_name='Country Code')),
                ('name', models.CharField(help_text='Name of the country (e.g., Argentina)', max_length=100, verbose_name='Country Name')),
                ('phone_prefix', models.CharField(default='591', help_text='Country phone prefix (e.g., 54)', max_length=5, verbose_name='Phone Prefix')),
                ('address', models.TextField(blank=True, help_text='Business address for this country', max_length=255, null=True, verbose_name='Address')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('tel', models.CharField(blank=True, help_text='Phone number for this country', max_length=20, null=True, verbose_name='Phone')),
                ('cel', models.CharField(blank=True, help_text='WhatsApp number for this country', max_length=20, null=True, verbose_name='WhatsApp / Celular 1')),
                ('mjeGlobo', models.CharField(blank=True, help_text='Leave blank to hide WhatsApp bubble', max_length=128, null=True, verbose_name='WhatsApp Bubble Message')),
                ('cel2', models.CharField(blank=True, help_text='Secondary phone number', max_length=20, null=True, verbose_name='Celular 2')),
                ('email', models.EmailField(blank=True, help_text='Contact email for this country', max_length=255, null=True, verbose_name='Email Address')),
                ('icon', models.FileField(blank=True, help_text='Website icon/logo for this country (SVG, PNG, JPG)', null=True, upload_to='icons/', verbose_name='Icon')),
                ('theme', models.CharField(choices=[('serprolim', 'Serprolim (Original)'), ('limpio', 'Limpio (Compatible)'), ('limpio-ya', 'Limpio Ya (Logo Colors)'), ('multisane', 'MultiSane (Emerald Green)')], default='serprolim', help_text='Select the color palette for this country', max_length=50, verbose_name='Theme / Palette')),
            ],
            options={
                'verbose_name': 'Country Settings',
                'verbose_name_plural': 'Country Settings',
            },
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='phone_prefix',
            field=models.CharField(default='591', help_text='Country phone prefix (e.g., 591)', max_length=5, verbose_name='Phone Prefix'),
        ),
    ]
