# Generated by Django 5.1.15 on 2026-02-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favicon', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='faviconsettings',
                    table='wfavicon_faviconsettings',
                ),
            ],
            database_operations=[],  # Table already exists with this name
        ),
    ]
