# Generated by Django 6.0.2 on 2026-03-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingsettings',
            name='adsense',
            field=models.TextField(blank=True, help_text='Snippet de AdSense — obtenido desde adsense.google.com', null=True, verbose_name='Google AdSense'),
        ),
        migrations.AlterField(
            model_name='trackingsettings',
            name='body_scripts',
            field=models.TextField(blank=True, help_text='Código HTML/JS a inyectar al cierre del <body>', null=True, verbose_name='Scripts adicionales en <body>'),
        ),
        migrations.AlterField(
            model_name='trackingsettings',
            name='fb_pixel',
            field=models.TextField(blank=True, help_text='Snippet completo del Pixel de Meta Ads (incluye el código base)', null=True, verbose_name='Facebook / Meta Pixel'),
        ),
        migrations.AlterField(
            model_name='trackingsettings',
            name='google_ads',
            field=models.TextField(blank=True, help_text='Snippet de conversión de Google Ads', null=True, verbose_name='Google Ads'),
        ),
        migrations.AlterField(
            model_name='trackingsettings',
            name='google_analytics',
            field=models.TextField(blank=True, help_text='Snippet de GA4 — obtenido desde analytics.google.com', null=True, verbose_name='Google Analytics'),
        ),
        migrations.AlterField(
            model_name='trackingsettings',
            name='gtm',
            field=models.TextField(blank=True, help_text='Pegar el snippet completo de GTM (incluye la etiqueta <script>)', null=True, verbose_name='Google Tag Manager'),
        ),
        migrations.AlterField(
            model_name='trackingsettings',
            name='head_scripts',
            field=models.TextField(blank=True, help_text='Cualquier otro código HTML/JS a inyectar en el <head>', null=True, verbose_name='Scripts adicionales en <head>'),
        ),
        migrations.AlterField(
            model_name='trackingsettings',
            name='open_graph',
            field=models.TextField(blank=True, help_text='Meta tags OG globales del sitio. Ej: og:image, og:site_name, fb:app_id', null=True, verbose_name='Open Graph (Facebook / WhatsApp / LinkedIn)'),
        ),
    ]
